# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rj0zVnlxPiENyedebB08D7xi7JBN6Tr0
"""

import requests
import csv
import time

url = "https://random-data-api.com/api/users/random_user"

with open("users.csv", mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["id", "FirstName", "LastName", "Username", "Email", "Avatar", "Gender", "DoB", "Address"])
    for i in range(10):
        response = requests.get(url).json()
        writer.writerow([response["id"], response["first_name"], response["last_name"], response["username"], response["email"], response["avatar"], response["gender"], response["date_of_birth"], response["address"]])
        time.sleep(1)

import pandas as pd
df = pd.read_csv("users.csv")
df.head(10)

import csv
import datetime

with open("users.csv", mode="r") as file:
    reader = csv.reader(file)
    next(reader)  # Skip the header row
    for row in reader:
        dob = datetime.date.fromisoformat(row[7])
        age = datetime.date.today().year - dob.year
        print(f"{row[1]} {row[2]} is {age} years old.")

import csv
import datetime

with open("users.csv", mode="r") as file:
    reader = csv.reader(file)
    next(reader)  # Skip the header row
    user_input = input("Enter ID or username of user: ")
    for row in reader:
        if row[0] == user_input or row[3] == user_input:
            dob = datetime.date.fromisoformat(row[7])
            age = datetime.date.today().year - dob.year
            print(f"ID: {row[0]}\nFirst Name: {row[1]}\nLast Name: {row[2]}\nUsername: {row[3]}\nEmail: {row[4]}\nAvatar: {row[5]}\nGender: {row[6]}\nDate of Birth: {row[7]}\nAddress: {row[8]}\nAge: {age}")
            break
    else:
        print("User not found.")